name: Build EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Show packages
        run: |
          pip show paddlex
          pip list
    
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install "paddlex[ocr]"
          python -m pip install pyinstaller

      - name: Check paddle
        run: |
          pip show paddlepaddle
    
      - name: Install OCR dependencies
        run: |
          python -m pip install "paddlex[ocr-core]"
    
      - name: Show paddlex package
        run: |
          python -m pip show paddlex
    
      - name: Verify OCR
        run: |
          python -c "from paddleocr import PaddleOCR; print('import OK')"
          
      - name: Verify PaddleOCR
        run: |
          python -c "from paddleocr import PaddleOCR; ocr=PaddleOCR(lang='japan'); print('OCR OK')"

      - name: Build
        run: |
          pyinstaller `
            --windowed `
            --collect-data paddleocr `
            --collect-data paddlex `
            --collect-data paddle `
            main.py

      - uses: actions/upload-artifact@v4
        with:
          name: myocr
          path: dist
